# Home page route
index:
  path: /
  controller: App\Controller\HomeController::index
app_register:
  path: /register
  controller: App\Controller\RegistrationController::register
app_verify_email:
  path: /verify/email
  controller: App\Controller\RegistrationController::verifyUserEmail
login:
  path: /login
  controller: App\Controller\LoginController::index
logout:
  path: /logout
  controller: App\Controller\LoginController::logout
